title: .blog//alchemicalapples
email: dbralir@gmail.com
description: >-
  Yet another blog/portfolio.
  C++ elitism. Amatuer gamedev. Romance.
github_username: alchemicalapples

collections:
  games:
    output: true
    permalink: /:collection/:title/

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

